name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      PYTEST_ADDOPTS: "--run-integration --showlocals -vv --durations=10 --reruns 5 --only-rerun subprocess.CalledProcessError"
    strategy:
      fail-fast: false
      matrix:
        py:
          - '3.8'
          - '3.7'

    steps:
      - uses: actions/checkout@v2

      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox
        run: python -m pip install .[test]
      - name: Run test suite
        run: pytest .
